/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 olkap_logo.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/olkap_logo.gltf')
  const groupRef = useRef()
  const isMobile = /iPhone|iPad|iPod|Android/i.test(navigator.userAgent);
  const rotationSpeed = isMobile ? 0.005 : 0.003;

  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.x += rotationSpeed
      groupRef.current.rotation.y += rotationSpeed
    }
  })
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh geometry={nodes['SVG_Logo-06svg_1mmstl'].geometry} material={materials.Material_0} scale={[0.08, 0.08, 0.127]} />
    </group>
  )
}

useGLTF.preload('/models/olkap_logo.gltf')
